version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
    container_name: movie-server
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - API_KEY=${API_KEY}
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_API_KEY: ${VITE_API_KEY}
    container_name: movie-frontend
    ports:
      - "5173:80"
    depends_on:
      - server
